In [36]:
import random
import pandas as pd

lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
print(data.head(20))

   whoAmI
0   human
1   robot
2   robot
3   human
4   robot
5   robot
6   robot
7   human
8   robot
9   robot
10  human
11  robot
12  human
13  robot
14  human
15  human
16  human
17  robot
18  human
19  human

In [37]:
pd.get_dummies(data['whoAmI'])

    human  robot
0    True  False
1   False   True
2   False   True
3    True  False
4   False   True
5   False   True
6   False   True
7    True  False
8   False   True
9   False   True
10   True  False
11  False   True
12   True  False
13  False   True
14   True  False
15   True  False
16   True  False
17  False   True
18   True  False
19   True  False

In [57]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder(sparse_output=False) 
onehot_encoded = onehot_encoder.fit_transform(data) 
one_hot = pd.DataFrame(onehot_encoded)
print(one_hot.head(20))

      0    1
0   1.0  0.0
1   0.0  1.0
2   0.0  1.0
3   1.0  0.0
4   0.0  1.0
5   0.0  1.0
6   0.0  1.0
7   1.0  0.0
8   0.0  1.0
9   0.0  1.0
10  1.0  0.0
11  0.0  1.0
12  1.0  0.0
13  0.0  1.0
14  1.0  0.0
15  1.0  0.0
16  1.0  0.0
17  0.0  1.0
18  1.0  0.0
19  1.0  0.0